version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: oroshine_db
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oroshine_net
    deploy:
      resources:
        limits:
          memory: 256M
    command: postgres -c shared_buffers=32MB -c effective_cache_size=64MB

  redis:
    image: redis:7-alpine
    container_name: oroshine_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 32mb --maxmemory-policy allkeys-lru --appendonly no
    networks:
      - oroshine_net
    deploy:
      resources:
        limits:
          memory: 64M

  web:
    image: nikhil2523/oroshine:latest
    container_name: oroshine_web
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - oroshine_net
    deploy:
      resources:
        limits:
          memory: 450M

  celery_worker:
    image: nikhil2523/oroshine:latest
    container_name: oroshine_celery_worker
    restart: always
    env_file: .env
    depends_on:
      - web
      - redis
    # OPTIMIZATION: Low concurrency for t2.micro
    command: celery -A oroshine_app worker --loglevel=info --concurrency=1
    networks:
      - oroshine_net
    deploy:
      resources:
        limits:
          memory: 150M

  celery_beat:
    image: nikhil2523/oroshine:latest
    container_name: oroshine_celery_beat
    restart: always
    env_file: .env
    depends_on:
      - web
      - redis
    command: celery -A oroshine_app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - oroshine_net
    deploy:
      resources:
        limits:
          memory: 100M

  nginx:
    image: nginx:1.25-alpine
    container_name: oroshine_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/robots.txt:/usr/share/nginx/html/robots.txt:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    networks:
      - oroshine_net
    deploy:
      resources:
        limits:
          memory: 64M

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  oroshine_net:
    driver: bridge