
# services:
#   web:
#     build:
#       context: ./oroshine_app
#     container_name: oroshine_web
#     command: ./entrypoint.sh
#     ports:
#       - "8000:8000"
#     env_file: .env
#     volumes:
#       - ./oroshine_app:/app
#       - static_volume:/app/staticfiles
#       - media_volume:/app/media
#     depends_on:
#       - db
#       - redis

#   db:
#     image: postgres:15
#     container_name: oroshine_db
#     restart: always
#     env_file: .env
#     environment:
#       - POSTGRES_DB=${PG_DB}
#       - POSTGRES_USER=${PG_USER}
#       - POSTGRES_PASSWORD=${PG_PASSWORD}
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:7
#     container_name: oroshine_redis
#     restart: always
#     ports:
#       - "6379:6379"

#   celery_worker:
#     build:
#       context: ./oroshine_app
#     container_name: oroshine_celery_worker
#     command: celery -A oroshine_app worker -l info --concurrency=2
#     env_file: .env
#     volumes:
#       - ./oroshine_app:/app
#       - media_volume:/app/media
#     depends_on:
#       - db
#       - redis
#     restart: unless-stopped

#   celery_beat:
#     build:
#       context: ./oroshine_app
#     container_name: oroshine_celery_beat
#     command: celery -A oroshine_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#     env_file: .env
#     volumes:
#       - ./oroshine_app:/app
#     depends_on:
#       - db
#       - redis
#     restart: unless-stopped

# volumes:
#   pgdata:
#   static_volume:
#   media_volume:



version: "3.9"

services:
  web:
    image: nikhil2523/oroshine:latest
    container_name: oroshine_web
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000

  db:
    image: postgres:15
    container_name: oroshine_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: oroshine_redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    image: nikhil2523/oroshine:latest
    container_name: oroshine_celery
    command: celery -A oroshine_app worker -l info
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    image: nikhil2523/oroshine:latest
    container_name: oroshine_celery_beat
    command: celery -A oroshine_app beat -l info
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:alpine
    container_name: oroshine_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
